/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolgrading;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author kmike
 */
public class AddGrades extends javax.swing.JFrame {

    /**
     * Creates new form AddGrades
     */
    public AddGrades() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        addStudentLabel = new javax.swing.JLabel();
        addResultLabel = new javax.swing.JLabel();
        checkPerfomanceLabel = new javax.swing.JLabel();
        AnalyseClassLabel = new javax.swing.JLabel();
        ReportformLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        gradepanel = new javax.swing.JPanel();
        checkPeformance = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        admission_no = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_results = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        comboForm1 = new javax.swing.JComboBox<>();
        comboTerm1 = new javax.swing.JComboBox<>();
        analyseclassPanel = new javax.swing.JPanel();
        ReportPanel = new javax.swing.JPanel();
        addResultPanel = new javax.swing.JPanel();
        comboForm = new javax.swing.JComboBox<>();
        admField = new javax.swing.JTextField();
        comboTerm = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submitresultsbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        engfield = new javax.swing.JTextField();
        geoField = new javax.swing.JTextField();
        bioField = new javax.swing.JTextField();
        chemField = new javax.swing.JTextField();
        histField = new javax.swing.JTextField();
        creField = new javax.swing.JTextField();
        AgricField = new javax.swing.JTextField();
        compField = new javax.swing.JTextField();
        kiswField = new javax.swing.JTextField();
        mathsField = new javax.swing.JTextField();
        bstField = new javax.swing.JTextField();
        phycField = new javax.swing.JTextField();
        hscField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        comboExam = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDIT STUDENT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel7.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel7.setText("STUDENT EDITOR ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(null);

        jPanel5.setOpaque(false);

        addStudentLabel.setBackground(new java.awt.Color(204, 204, 255));
        addStudentLabel.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        addStudentLabel.setForeground(new java.awt.Color(255, 102, 0));
        addStudentLabel.setText("Add student ");
        addStudentLabel.setOpaque(true);
        addStudentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentLabelMouseClicked(evt);
            }
        });

        addResultLabel.setBackground(new java.awt.Color(204, 204, 255));
        addResultLabel.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        addResultLabel.setForeground(new java.awt.Color(255, 102, 0));
        addResultLabel.setText("Add results");
        addResultLabel.setOpaque(true);
        addResultLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addResultLabelMouseClicked(evt);
            }
        });

        checkPerfomanceLabel.setBackground(new java.awt.Color(204, 204, 255));
        checkPerfomanceLabel.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        checkPerfomanceLabel.setForeground(new java.awt.Color(255, 102, 0));
        checkPerfomanceLabel.setText("Check per..");
        checkPerfomanceLabel.setOpaque(true);
        checkPerfomanceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkPerfomanceLabelMouseClicked(evt);
            }
        });

        AnalyseClassLabel.setBackground(new java.awt.Color(204, 204, 255));
        AnalyseClassLabel.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        AnalyseClassLabel.setForeground(new java.awt.Color(255, 102, 0));
        AnalyseClassLabel.setText("Analyse class");
        AnalyseClassLabel.setOpaque(true);
        AnalyseClassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnalyseClassLabelMouseClicked(evt);
            }
        });

        ReportformLabel.setBackground(new java.awt.Color(204, 204, 255));
        ReportformLabel.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        ReportformLabel.setForeground(new java.awt.Color(255, 102, 0));
        ReportformLabel.setText("Print  R form");
        ReportformLabel.setOpaque(true);
        ReportformLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportformLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addStudentLabel)
                            .addComponent(addResultLabel)
                            .addComponent(AnalyseClassLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(checkPerfomanceLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ReportformLabel)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(addStudentLabel)
                .addGap(38, 38, 38)
                .addComponent(addResultLabel)
                .addGap(37, 37, 37)
                .addComponent(checkPerfomanceLabel)
                .addGap(36, 36, 36)
                .addComponent(AnalyseClassLabel)
                .addGap(28, 28, 28)
                .addComponent(ReportformLabel)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel5);
        jPanel5.setBounds(0, 0, 110, 490);

        jLabel1.setIcon(new javax.swing.ImageIcon("H:\\OTHERS\\Wallpapers\\screen saver\\DesktopBackground\\DesktopBackground\\244295.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel7.add(jLabel1);
        jLabel1.setBounds(0, 0, 110, 500);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        gradepanel.setLayout(new java.awt.CardLayout());

        checkPeformance.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setText("Student adm ");

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("CHECK STUDENT PERFORMANCE");
        jLabel8.setOpaque(true);

        jLabel10.setText("Form");

        table_results.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(table_results);

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboForm1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "form1exams2016", "form2exams2016", "form3exams2016", "form4exams2016", " " }));

        comboTerm1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Term 1", "Term 2", "Term 3" }));
        comboTerm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTerm1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkPeformanceLayout = new javax.swing.GroupLayout(checkPeformance);
        checkPeformance.setLayout(checkPeformanceLayout);
        checkPeformanceLayout.setHorizontalGroup(
            checkPeformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPeformanceLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(checkPeformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkPeformanceLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkPeformanceLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admission_no, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        checkPeformanceLayout.setVerticalGroup(
            checkPeformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPeformanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkPeformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admission_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jButton1)
                    .addComponent(comboForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        gradepanel.add(checkPeformance, "card4");

        analyseclassPanel.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout analyseclassPanelLayout = new javax.swing.GroupLayout(analyseclassPanel);
        analyseclassPanel.setLayout(analyseclassPanelLayout);
        analyseclassPanelLayout.setHorizontalGroup(
            analyseclassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        analyseclassPanelLayout.setVerticalGroup(
            analyseclassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        gradepanel.add(analyseclassPanel, "card6");

        ReportPanel.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout ReportPanelLayout = new javax.swing.GroupLayout(ReportPanel);
        ReportPanel.setLayout(ReportPanelLayout);
        ReportPanelLayout.setHorizontalGroup(
            ReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        ReportPanelLayout.setVerticalGroup(
            ReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        gradepanel.add(ReportPanel, "card2");

        addResultPanel.setBackground(new java.awt.Color(204, 255, 204));
        addResultPanel.setForeground(new java.awt.Color(255, 0, 102));

        comboForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "form1exams2016", "form2exams2016", "form3exams2016", "form4exams2016", " " }));

        admField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admFieldActionPerformed(evt);
            }
        });

        comboTerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Term 1", "Term 2", "Term 3" }));
        comboTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTermActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter stdt Adm");

        jLabel3.setText("form");

        jLabel4.setText("term");

        submitresultsbtn.setText("Submit results");
        submitresultsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitresultsbtnActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("ADD MARKS ");
        jLabel9.setOpaque(true);

        engfield.setForeground(new java.awt.Color(255, 51, 51));
        engfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "English", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        engfield.setOpaque(false);

        geoField.setForeground(new java.awt.Color(255, 51, 51));
        geoField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Geo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        geoField.setOpaque(false);

        bioField.setForeground(new java.awt.Color(255, 51, 51));
        bioField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biology", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        bioField.setOpaque(false);

        chemField.setForeground(new java.awt.Color(255, 51, 51));
        chemField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chemistry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        chemField.setOpaque(false);

        histField.setForeground(new java.awt.Color(255, 51, 51));
        histField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        histField.setOpaque(false);
        histField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histFieldActionPerformed(evt);
            }
        });

        creField.setForeground(new java.awt.Color(255, 51, 51));
        creField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CRE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        creField.setOpaque(false);

        AgricField.setForeground(new java.awt.Color(255, 51, 51));
        AgricField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agric", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        AgricField.setOpaque(false);

        compField.setForeground(new java.awt.Color(255, 51, 51));
        compField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Computer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        compField.setOpaque(false);

        kiswField.setForeground(new java.awt.Color(255, 51, 51));
        kiswField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kiswahili", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        kiswField.setOpaque(false);

        mathsField.setForeground(new java.awt.Color(255, 51, 51));
        mathsField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Maths", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        mathsField.setOpaque(false);

        bstField.setForeground(new java.awt.Color(255, 51, 51));
        bstField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bst", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        bstField.setOpaque(false);

        phycField.setForeground(new java.awt.Color(255, 51, 51));
        phycField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Physics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        phycField.setOpaque(false);

        hscField.setForeground(new java.awt.Color(255, 51, 51));
        hscField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HSC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 1, 14))); // NOI18N
        hscField.setOpaque(false);

        jButton2.setText("update");

        comboExam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opener", "midterm", "endterm" }));

        jLabel5.setText("Exam");

        javax.swing.GroupLayout addResultPanelLayout = new javax.swing.GroupLayout(addResultPanel);
        addResultPanel.setLayout(addResultPanelLayout);
        addResultPanelLayout.setHorizontalGroup(
            addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addResultPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addResultPanelLayout.createSequentialGroup()
                        .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(admField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(comboExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addResultPanelLayout.createSequentialGroup()
                        .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chemField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mathsField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(engfield, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addResultPanelLayout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bioField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addResultPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35))
                                    .addComponent(phycField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(geoField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(histField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(kiswField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bstField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgricField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hscField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitresultsbtn)
                            .addComponent(jButton2))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        addResultPanelLayout.setVerticalGroup(
            addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addResultPanelLayout.createSequentialGroup()
                .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addResultPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(addResultPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kiswField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phycField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgricField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mathsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chemField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(histField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hscField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(compField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitresultsbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(62, 62, 62))
        );

        gradepanel.add(addResultPanel, "card3");

        jPanel1.add(gradepanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentLabelMouseClicked
        AddStudent addStudent = new AddStudent();
        addStudent.setVisible(true);
    }//GEN-LAST:event_addStudentLabelMouseClicked

    private void addResultLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addResultLabelMouseClicked
        gradepanel.removeAll();
        gradepanel.add(addResultPanel);
        gradepanel.repaint();
        gradepanel.revalidate();
    }//GEN-LAST:event_addResultLabelMouseClicked

    private void checkPerfomanceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkPerfomanceLabelMouseClicked
        gradepanel.removeAll();
        gradepanel.add(checkPeformance);
        gradepanel.repaint();
        gradepanel.revalidate();

    }//GEN-LAST:event_checkPerfomanceLabelMouseClicked

    private void AnalyseClassLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnalyseClassLabelMouseClicked
        gradepanel.removeAll();
        gradepanel.add(analyseclassPanel);
        gradepanel.repaint();
        gradepanel.revalidate();
    }//GEN-LAST:event_AnalyseClassLabelMouseClicked

    private void ReportformLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportformLabelMouseClicked
        gradepanel.removeAll();
        gradepanel.add(ReportPanel);
        gradepanel.repaint();
        gradepanel.revalidate();
    }//GEN-LAST:event_ReportformLabelMouseClicked

    private void admFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admFieldActionPerformed

    private void histFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_histFieldActionPerformed

    private void submitresultsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitresultsbtnActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolgrading", "root", "");
            PreparedStatement pps = con.prepareStatement("SELECT * FROM `students data` WHERE `adm-no`=?");            
            pps.setString(1, admField.getText());
            ResultSet rs = pps.executeQuery();
            if (rs.next()) {
                
//other
                String admyear=rs.getString("doAdmission");
                String classofAdm=rs.getString("classOfAdmission");
                String table = comboForm.getSelectedItem().toString();
                char ch1=(char)table.charAt(10);
                char ch2=(char)table.charAt(11);
                char ch3=(char)table.charAt(12);
                char ch4=(char)table.charAt(13);
                char ch5=(char)table.charAt(4);
                char ch6=(char)classofAdm.charAt(5);

                
                String dbTable=ch1+""+ch2+""+ch3+""+ch4;
                String []admYear=admyear.split(",");                
               // System.out.println(admYear[1] + classofAdm +dbTable);
               if(admYear[1].contains(dbTable)) {
                  //System.out.println("Allowed to add data");
                   if(ch5==ch6) {
                  //System.out.println("Allowed to add data");       
//other                
                PreparedStatement resultStmt = con.prepareStatement("SELECT * FROM `" + table + "` WHERE `adm` =? AND`Term`=? AND`examNo`=?");
                resultStmt.setString(1, admField.getText());
                resultStmt.setString(2, comboTerm.getSelectedItem().toString());
                resultStmt.setString(3, (String) comboExam.getSelectedItem());
                ResultSet result = resultStmt.executeQuery();
                if (result.next()) {
                    JOptionPane.showMessageDialog(null, "Results Already Exists");
                } else {
                    PreparedStatement ps = con.prepareStatement("INSERT INTO `" + table + "`(`adm`, `examNo`, `Term`, `english`,"
                            + " `kiswahili`, `maths`, `chem`, `bio`, `phyc`, `hist`, `geo`, `cre`, `agric`, `homescience`, `comp`, `bst`)"
                            + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, admField.getText());
                    ps.setString(2, (String) comboExam.getSelectedItem());
                    ps.setString(3, comboTerm.getSelectedItem().toString());
                    ps.setString(4, engfield.getText());
                    ps.setString(5, kiswField.getText());
                    ps.setString(6, mathsField.getText());
                    ps.setString(7, chemField.getText());
                    ps.setString(8, bioField.getText());
                    ps.setString(9, phycField.getText());
                    ps.setString(10, histField.getText());
                    ps.setString(11, geoField.getText());
                    ps.setString(12, creField.getText());
                    ps.setString(13, AgricField.getText());
                    ps.setString(14, hscField.getText());
                    ps.setString(15, compField.getText());
                    ps.setString(16, bstField.getText());

                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(null, "Added successfully");
                    }
                }
                   } else {
                    JOptionPane.showMessageDialog(null, "Youve inputed the wrong class"); 
                }
                  
                } else {
                  JOptionPane.showMessageDialog(null, "Wrong year ");  
                }
                
                
            } else {
                JOptionPane.showMessageDialog(null, "invalid details details");

            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_submitresultsbtnActionPerformed

    private void comboTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTermActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
             String form =comboForm1.getSelectedItem().toString();
            String sql = "SELECT `examNo`, `english`, `kiswahili`, `maths`, `chem`, `bio`,"
                    + " `phyc`, `hist`, `geo`, `cre`, `agric`, `homescience`, `comp`, "
                    + "`bst`  FROM `" + form + "` WHERE `adm`=? AND `Term`=? ";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolgrading", "root", "");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, admission_no.getText());
            ps.setString(2, comboTerm1.getSelectedItem().toString());

            ResultSet rs = ps.executeQuery();
            table_results.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboTerm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTerm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTerm1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgricField;
    private javax.swing.JLabel AnalyseClassLabel;
    private javax.swing.JPanel ReportPanel;
    private javax.swing.JLabel ReportformLabel;
    private javax.swing.JLabel addResultLabel;
    private javax.swing.JPanel addResultPanel;
    private javax.swing.JLabel addStudentLabel;
    private javax.swing.JTextField admField;
    private javax.swing.JTextField admission_no;
    private javax.swing.JPanel analyseclassPanel;
    private javax.swing.JTextField bioField;
    private javax.swing.JTextField bstField;
    private javax.swing.JPanel checkPeformance;
    private javax.swing.JLabel checkPerfomanceLabel;
    private javax.swing.JTextField chemField;
    private javax.swing.JComboBox<String> comboExam;
    private javax.swing.JComboBox<String> comboForm;
    private javax.swing.JComboBox<String> comboForm1;
    private javax.swing.JComboBox<String> comboTerm;
    private javax.swing.JComboBox<String> comboTerm1;
    private javax.swing.JTextField compField;
    private javax.swing.JTextField creField;
    private javax.swing.JTextField engfield;
    private javax.swing.JTextField geoField;
    private javax.swing.JPanel gradepanel;
    private javax.swing.JTextField histField;
    private javax.swing.JTextField hscField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kiswField;
    private javax.swing.JTextField mathsField;
    private javax.swing.JTextField phycField;
    private javax.swing.JButton submitresultsbtn;
    private javax.swing.JTable table_results;
    // End of variables declaration//GEN-END:variables
}
